# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: GET
title-normal: CLASS UP
email: rusamgr8@gmail.com
description: GetClassUp started with the motto to help human beings to exude their passion. This was created with full love and respect to benefit people. Part of the material is also used from learnings of one of the best Leadership Mentor, Robin Sharma.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
author: "Rushabh Soni"
street_address: 
city: 
state: 
zip_code:
country: 
phone: 

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 2

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
